### ISSUE TITLE
Renders tab links to Fandom Wiki instead of Miraheze Wiki

### ISSUE THREAD

**Issue by Ylimegirl** [myang5/twst-wiki-parser#5]
Old URL: https://twisted-wonderland.fandom.com

New URL: https://twistedwonderland.miraheze.org

**Comment by Ylimegirl** [comment]
The links now go to https://twisted-wonderland.miraheze.org, which is close, but not quite right--there's no dash in the Miraheze URL.

**Comment by myang5** [comment]
Oop, thanks for catching!
